# ╔════════════════════════════════════════════════════════════════════════════╗
# ║                               Hyprlock                                   ║
# ╚════════════════════════════════════════════════════════════════════════════╝

source = /home/Josh/.cache/wal/colors.css

bezier = ease, 0.16, 1, 0.3, 1
animation = fade, 1, 15, ease

general {
    grace = 1
    fail_timeout = 1000
}
background {
    monitor =
    $WALL =             /home/Josh/.cache/swww
    path =              $WALL/cache
    color =             rgba(25, 20, 20, 1.0)
    blur_passes =       2
    blur_size =         3
    noise =             0.0117
    contrast =          0.8916
    brightness =        0.8172
    vibrancy =          0.1696
    vibrancy_darkness = 0.0
}
shape {
    monitor = ASUSTek COMPUTER INC VG27A M3LMQS414609 #DP-1
    size = 600, 1440
    color = rgba(15, 15, 15, 0.5)
    rounding = 0
    border_size = 0
    border_color = rgba(0, 207, 230, 1.0)
    rotate = 0
    xray = false # if true, make a "hole" in the background (rectangle of specified size, no rotation)

    position = 0, 0
    halign = left
    valign = center
}
input-field {
    monitor =           ASUSTek COMPUTER INC VG27A M3LMQS414609 #DP-1
    size =              350, 60
    rounding =          10
    outline_thickness = 1
    dots_size =         0.25 # Scale of input-field height, 0.2 - 0.8 Default: 0.33
    dots_spacing =      0.35 # Scale of dots' absolute size, 0.0 - 1.0 Default: 0.15
    dots_rounding =     6
    dots_center =       true
    outer_color =       rgba(50, 50, 50, 0.5) #(25, 25, 25, 0.5)
    inner_color =       rgba(15, 15, 15, 0.2) #(15, 15, 15, 0.4)
    font_color =        rgb(180, 180, 180)
    fade_on_empty =     true
    fade_timeout =      1000
    placeholder_text =  <i>Password</i> # Text rendered in the input box when it's empty.
    hide_input =        false
    shadow_passes =     2
    check_color =       rgb(204, 136, 34)
    fail_color =        rgb(204, 34, 34) # if authentication failed, changes outer_color and fail message color
    fail_text =         <i>$FAIL <b>($ATTEMPTS)</b></i> # can be set to empty
    fail_transition =   300 # transition time in ms between normal outer_color and fail_color
    capslock_color =    -2

    position = 115, -140 # 0, -140
    halign =   left #center
    valign =   center
}
label {
    monitor =       ASUSTek COMPUTER INC VG27A M3LMQS414609 #DP-1
    text =          Welcome, $USER
    color =         rgba(200, 200, 200, 1.0)
    font_size =     25
    font_family =   Roboto
    shadow_passes = 3

    position = 180, -40 # 0, -40
    halign =   left #center
    valign =   center
}

# Time

label {
    monitor =       ASUSTek COMPUTER INC VG27A M3LMQS414609 #DP-1
    text =          cmd[update:1000] date +"%H"
    color =         rgba(200, 200, 200, 1.0)
    font_size =     112 #72
    font_family =   Roboto
    shadow_passes = 3

    position = 210, -350 # 0, -450
    halign =   left #center
    valign =   top
}
label {
    monitor =       ASUSTek COMPUTER INC VG27A M3LMQS414609 #DP-1
    text =          cmd[update:1000] date +"%M"
    color =         rgba(200, 200, 200, 1.0)
    font_size =     112 #72
    font_family =   Roboto
    shadow_passes = 3

    position = 210, -500 # 0, -450
    halign =   left #center
    valign =   top
}

# Weather

#label {
#    monitor =       DP-1
#    text =          cmd[update:1000] curl wttr.in | sed -n '4p' | awk '{print $4, $5}'| sed 's/\x1B\[[0-9;]\{1,\}[A-Za-z]//g'
#    color =         rgba(200, 200, 200, 1.0)
#    font_size =     18
#    font_family =   Roboto
#    shadow_passes = 3
#
#    position = 20, 20
#    halign =   left
#    valign =   bottom
#}

# Status icons below
