# ╔════════════════════════════════════════════════════════════════════════════╗
# ║                                 Autostart                                  ║
# ╚════════════════════════════════════════════════════════════════════════════╝

exec-once = /home/Josh/.config/hypr/Scripts/Launch/startup_v3.sh
exec-once = [workspace 2 silent;noanim] /usr/bin/steam %U
exec-once = [workspace special:tools silent;noanim] /usr/bin/localsend %U

exec = hyprpm reload -nn
exec = hyprctl setcursor Qogir-cursors 24

exec-shutdown = pkill hypridle
