# ╔════════════════════════════════════════════════════════════════════════════╗
# ║                                Decorations                                 ║
# ╚════════════════════════════════════════════════════════════════════════════╝

decoration {
    rounding =            6
    rounding_power =      10.0
    active_opacity =      0.85
    inactive_opacity =    0.8
    fullscreen_opacity =  1.0

    dim_inactive =        false
    dim_strength =        0.5
    dim_special =         0.2
    dim_around =          0.4

    shadow {
        enabled =       true
        range =         true
        render_power =  3
        sharp =         false
        ignore_window = true
        color =         0xee1a1a1a
        offset =        0 0
        scale =         1.0
    }

    blur {
        enabled =           true
        size =              4
        passes =            3
        new_optimizations = true
        ignore_opacity =    true
        popups =            true
        special =           false
    }
}
