# ╔════════════════════════════════════════════════════════════════════════════╗
# ║                                  Display                                   ║
# ╚════════════════════════════════════════════════════════════════════════════╝

# monitor = monitor,resolution@refreshrate,position,scaling
$right = ASUSTek COMPUTER INC VG27A M3LMQS414609
$left = ASUSTek COMPUTER INC VG27A M2LMQS076205

monitor = desc:$right, 2560x1440@165, 2560x0, 1, vrr, 1
monitor = desc:$left,  2560x1440@144, 0x0,    1, vrr, 1
# ╔══════════════════════╗
# ║    Workspace Rules   ║
# ╚══════════════════════╝
workspace = 1,  monitor:desc:$right, default:true
workspace = 2,  monitor:desc:$right
workspace = 3,  monitor:desc:$right
workspace = 4,  monitor:desc:$right
workspace = 5,  monitor:desc:$right
workspace = 6,  monitor:desc:$left,  default:true
workspace = 7,  monitor:desc:$left
workspace = 8,  monitor:desc:$left
workspace = 9,  monitor:desc:$left
workspace = 10, monitor:desc:$left

workspace = special:terminal, on-created-empty:[float; size 99% 30.5%; move 0.55% 5%] kitty
workspace = special:special,  on-created-empty:[exec] /home/Josh/.config/hypr/Scripts/player.sh
workspace = special:tools,    on-created-empty: localsend
workspace = special:other,    on-created-empty:[pseudo] vesktop;
