# ╔════════════════════════════════════════════════════════════════════════════╗
# ║                              General Settings                              ║
# ╚════════════════════════════════════════════════════════════════════════════╝

general {
    gaps_in =             6
    gaps_out =            12
    gaps_workspaces =     4
    border_size =         2
    col.active_border =   rgba(ff4500ee) rgba(b72280ee) #45deg
    col.inactive_border = rgba(22282Dff)
    layout =              dwindle #hy3 as alternate
    allow_tearing =       true
    snap {
        enabled =        true
        window_gap =     10
        monitor_gap =    10
        border_overlap = false
    }
}

misc {
    animate_manual_resizes =       true
    disable_hyprland_logo =        true
    disable_splash_rendering =     true
    animate_mouse_windowdragging = true
    mouse_move_enables_dpms =      true
    key_press_enables_dpms =       true
    vrr =                          1
    initial_workspace_tracking =   0
}

render {
    direct_scanout =    2
    #explicit_sync =     1
    #explicit_sync_kms = 1
}

dwindle {
    pseudotile =     yes
    preserve_split = yes
}

binds {
    movefocus_cycles_fullscreen = false
}

cursor {
    no_hardware_cursors = 0
    default_monitor =     DP-1
    hide_on_key_press =   1
    persistent_warps =    1
    use_cpu_buffer =      1
}

debug {
    disable_logs = true
}
