# ╔════════════════════════════════════════════════════════════════════════════╗
# ║                                  Groups                                    ║
# ╚════════════════════════════════════════════════════════════════════════════╝
group {
    focus_removed_window = true
    col.border_active = rgba(ff4500ee) rgba(b72280ee)
    col.border_inactive = rgba(22282Dff)

    groupbar {
        col.active = rgba(ff4500ee) #rgba(b72280ee)
        col.inactive = rgba(595959aa)
        render_titles = false
        indicator_height = 10
        height = 8
        gaps_in = 8
        gaps_out = 2
        rounding = 3
        round_only_edges = false
    }
}
