# ╔════════════════════════════════════════════════════════════════════════════╗
# ║                               Screen Config                                ║
# ╚════════════════════════════════════════════════════════════════════════════╝
$primary = DP-1