# ╔════════════════════════════════════════════════════════════════════════════╗
# ║                                                                            ║
# ║                             Hyprland Config                              ║
# ║                                                                            ║
# ╚════════════════════════════════════════════════════════════════════════════╝

$hypr = ~/.config/hypr/conf

source = $hypr/display.conf
source = $hypr/autostart.conf
source = $hypr/environment.conf
source = $hypr/input.conf
source = $hypr/general.conf
source = $hypr/groups.conf
source = $hypr/decoration.conf
source = $hypr/animation.conf
source = $hypr/plugins.conf
source = $hypr/windowrule.conf
source = $hypr/binds/hyprkeybinds.conf
#source = $hypr/binds/hy3keybinds.conf
