# ╔════════════════════════════════════════════════════════════════════════════╗
# ║                                 Autostart                                  ║
# ╚════════════════════════════════════════════════════════════════════════════╝
exec-once = /home/Josh/.config/hypr/Scripts/Launch/startup_v3.sh
exec-once = [workspace special:tools silent] /usr/bin/localsend %U
exec-once = [workspace special:other silent] /usr/bin/vesktop --enable-features=UseOzonePlatform --ozone-platform=wayland --enable-features=WebRTCPipeWireCapturer,VaapiIgnoreDriverChecks,Vulkan,DefaultANGLEVulkan,VulkanFromANGLE

exec = hyprpm reload -n

exec-shutdown = pkill hypridle
