# ╔════════════════════════════════════════════════════════════════════════════╗
# ║                                  Display                                   ║
# ╚════════════════════════════════════════════════════════════════════════════╝
$right = ASUSTek COMPUTER INC VG27A M3LMQS414609
$left  = ASUSTek COMPUTER INC VG27A M2LMQS076205

# monitor = monitor,resolution@refreshrate,position,scaling
monitor = desc:$left,     2560x1440@144, 0x0,    1, vrr, 2
monitor = desc:$right,    2560x1440@165, 2560x0, 1, vrr, 2
monitor = stream-deck,    1280x800@60,   5120x0, 1, vrr, 2
monitor = remote-desktop, 2560x1440@165, 5120x0, 1, vrr, 2

# ╔══════════════════════╗
# ║    Workspace Rules   ║
# ╚══════════════════════╝
workspace = 1,  monitor:desc:$right, default:true
workspace = 2,  monitor:desc:$right
workspace = 3,  monitor:desc:$right
workspace = 4,  monitor:desc:$right
workspace = 5,  monitor:desc:$right
workspace = 6,  monitor:desc:$left,  default:true
workspace = 7,  monitor:desc:$left
workspace = 8,  monitor:desc:$left
workspace = 9,  monitor:desc:$left
workspace = 10, monitor:desc:$left

#Full topbar
#workspace = special:terminal, on-created-empty:[float; size (monitor_w*0.99) (monitor_h*0.305); move (monitor_w*0.0055) (monitor_h*0.045)] kitty
#Floating topbar
workspace = special:terminal, on-created-empty:[float; size (monitor_w*0.989) (monitor_h*0.305); move (monitor_w*0.0056) (monitor_h*0.055)] kitty

workspace = special:special,  on-created-empty:[exec] /home/Josh/.config/hypr/Scripts/player.sh
workspace = special:tools,    on-created-empty: localsend
workspace = special:other,    on-created-empty: /usr/bin/vesktop --enable-features=UseOzonePlatform --ozone-platform=wayland --enable-features=WebRTCPipeWireCapturer,VaapiIgnoreDriverChecks,Vulkan,DefaultANGLEVulkan,VulkanFromANGLE"
