# ╔════════════════════════════════════════════════════════════════════════════╗
# ║                                  Groups                                    ║
# ╚════════════════════════════════════════════════════════════════════════════╝
group {
    focus_removed_window = true
    col.border_active =    rgba(ff4500ee) rgba(b72280ee)
    col.border_inactive =  rgba(78787890)

    groupbar {
        blur =                      true
        gradients =                 true
        gradient_rounding =         3
        gradient_round_only_edges = false
        height =                    0
        col.active =                rgba(ff4500ee) rgba(4f2004ee)
        col.inactive =              rgba(595959aa)
        render_titles =             false
        gaps_in =                   6
        gaps_out =                  6
        rounding =                  3
        round_only_edges =          false
        indicator_height =          8
        keep_upper_gap =            false
    }
}
