#------------------------------------------------------------------------------------
# Input Settings
#------------------------------------------------------------------------------------
input {
    kb_layout =                   us
    numlock_by_default =          true
    follow_mouse =                2
    float_switch_override_focus = 2
    sensitivity =                 0
    force_no_accel =              true
    special_fallthrough =         true
}
